#!/usr/bin/env bash

echo "== deploy rds"

STACK_NAME="rds-basic"

# https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudformation/deploy/index.html
aws cloudformation deploy \
--template-file template.yaml \
--capabilities CAPABILITY_NAMED_IAM \
--no-execute-changeset \
--parameter-overrides VpcId="vpc-0b3cc61a9816023d8" WebServerSGGroupId="sg-09bb0d67256c87723" Subnets="subnet-0e64d42cbc27d1872,subnet-050cbe284cf3f1b62,subnet-0f5fd8d33a800e87f" \
--region ca-central-1 \
--stack-name $STACK_NAME


